medicaments_data = [
    {
        "id": 1,
        "nom": "Paracetamol",
        "max_duree_prise": 7,
        "forme": "Comprimé",
        "max_dose_jour": 500,
        "unite_dose": "mg",
        "stock": 200,
        "fournisseur": "SAIDAL",
        "prix_unitaire": 200,
        "indications": ["Douleur", "Fièvre"],
        "contre_indications": ["Maladie du foie"],
        "date_expiration": "2025-12-31"
    },
    {
        "id": 2,
        "nom": "Amoxicilline",
        "max_duree_prise": 10,
        "forme": "Capsule",
        "max_dose_jour": 500,
        "unite_dose": "mg",
        "stock": 150,
        "fournisseur": "SAIDAL",
        "prix_unitaire": 300,
        "indications": ["Infections bactériennes"],
        "contre_indications": ["Allergie à la pénicilline"],
        "date_expiration": "2024-11-30"
    },
    {
        "id": 3,
        "nom": "Ibuprofene",
        "max_duree_prise": 5,
        "forme": "Comprimé",
        "max_dose_jour": 400,
        "unite_dose": "mg",
        "stock": 100,
        "fournisseur": "Pharmalliance",
        "prix_unitaire": 250,
        "indications": ["Douleur", "Inflammation"],
        "contre_indications": ["Ulcères gastriques", "Insuffisance rénale"],
        "date_expiration": "2025-06-30"
    },
    {
        "id": 4,
        "nom": "Metformine",
        "max_duree_prise": 30,
        "forme": "Comprimé",
        "max_dose_jour": 850,
        "unite_dose": "mg",
        "stock": 300,
        "fournisseur": "Biopharm",
        "prix_unitaire": 150,
        "indications": ["Diabète de type 2"],
        "contre_indications": ["Insuffisance rénale sévère"],
        "date_expiration": "2026-01-01"
    },
    {
        "id": 5,
        "nom": "Omeprazole",
        "max_duree_prise": 14,
        "forme": "Gélule",
        "max_dose_jour": 20,
        "unite_dose": "mg",
        "stock": 250,
        "fournisseur": "Merinal",
        "prix_unitaire": 350,
        "indications": ["Reflux gastro-œsophagien", "Ulcères gastriques"],
        "contre_indications": ["Hypersensibilité aux IPP"],
        "date_expiration": "2025-09-15"
    },
    {
        "id": 6,
        "nom": "Atorvastatine",
        "max_duree_prise": 30,
        "forme": "Comprimé",
        "max_dose_jour": 10,
        "unite_dose": "mg",
        "stock": 180,
        "fournisseur": "Pfizer",
        "prix_unitaire": 500,
        "indications": ["Hypercholestérolémie"],
        "contre_indications": ["Maladie hépatique active"],
        "date_expiration": "2025-08-20"
    },
    {
        "id": 7,
        "nom": "Ciprofloxacine",
        "max_duree_prise": 10,
        "forme": "Comprimé",
        "max_dose_jour": 500,
        "unite_dose": "mg",
        "stock": 90,
        "fournisseur": "Pharmalliance",
        "prix_unitaire": 400,
        "indications": ["Infections bactériennes graves"],
        "contre_indications": ["Myasthénie"],
        "date_expiration": "2024-12-01"
    },
    {
        "id": 8,
        "nom": "Diclofenac",
        "max_duree_prise": 7,
        "forme": "Comprimé",
        "max_dose_jour": 50,
        "unite_dose": "mg",
        "stock": 200,
        "fournisseur": "SAIDAL",
        "prix_unitaire": 200,
        "indications": ["Douleur", "Inflammation"],
        "contre_indications": ["Insuffisance cardiaque sévère"],
        "date_expiration": "2025-03-01"
    },
    {
        "id": 9,
        "nom": "Prednisolone",
        "max_duree_prise": 14,
        "forme": "Comprimé",
        "max_dose_jour": 5,
        "unite_dose": "mg",
        "stock": 120,
        "fournisseur": "Merck",
        "prix_unitaire": 450,
        "indications": ["Affections inflammatoires"],
        "contre_indications": ["Infections fongiques systémiques"],
        "date_expiration": "2025-07-30"
    },
    {
        "id": 10,
        "nom": "Salbutamol",
        "max_duree_prise": 7,
        "forme": "Inhalateur",
        "max_dose_jour": 200,
        "unite_dose": "mcg",
        "stock": 300,
        "fournisseur": "GlaxoSmithKline",
        "prix_unitaire": 600,
        "indications": ["Asthme", "Bronchospasme"],
        "contre_indications": ["Cardiomyopathie obstructive"],
        "date_expiration": "2025-04-15"
    },
    {
        "id": 11,
        "nom": "Aspirine",
        "max_duree_prise": 30,
        "forme": "Comprimé",
        "max_dose_jour": 300,
        "unite_dose": "mg",
        "stock": 500,
        "fournisseur": "Bayer",
        "prix_unitaire": 100,
        "indications": ["Douleur", "Prévention des AVC"],
        "contre_indications": ["Ulcère actif", "Asthme sensible à l'aspirine"],
        "date_expiration": "2026-01-01"
    },
    {
        "id": 12,
        "nom": "Clarithromycine",
        "max_duree_prise": 7,
        "forme": "Comprimé",
        "max_dose_jour": 500,
        "unite_dose": "mg",
        "stock": 200,
        "fournisseur": "Abbott",
        "prix_unitaire": 450,
        "indications": ["Infections respiratoires", "Ulcère H. pylori"],
        "contre_indications": ["Insuffisance hépatique sévère"],
        "date_expiration": "2024-10-15"
    },
    {
        "id": 13,
        "nom": "Loratadine",
        "max_duree_prise": 14,
        "forme": "Comprimé",
        "max_dose_jour": 10,
        "unite_dose": "mg",
        "stock": 400,
        "fournisseur": "SAIDAL",
        "prix_unitaire": 150,
        "indications": ["Allergies", "Rhume des foins"],
        "contre_indications": ["Hypersensibilité à la loratadine"],
        "date_expiration": "2025-11-20"
    },
    {
        "id": 14,
        "nom": "Azithromycine",
        "max_duree_prise": 5,
        "forme": "Comprimé",
        "max_dose_jour": 500,
        "unite_dose": "mg",
        "stock": 100,
        "fournisseur": "Pfizer",
        "prix_unitaire": 600,
        "indications": ["Infections bactériennes"],
        "contre_indications": ["Insuffisance hépatique sévère"],
        "date_expiration": "2024-09-30"
    },
    {
        "id": 15,
        "nom": "Vitamine C",
        "max_duree_prise": 30,
        "forme": "Comprimé effervescent",
        "max_dose_jour": 1000,
        "unite_dose": "mg",
        "stock": 350,
        "fournisseur": "Pharmalliance",
        "prix_unitaire": 120,
        "indications": ["Déficit en vitamine C"],
        "contre_indications": ["Hyperoxalurie"],
        "date_expiration": "2025-05-01"
    },
    {
        "id": 16,
        "nom": "Furosemide",
        "max_duree_prise": 14,
        "forme": "Comprimé",
        "max_dose_jour": 40,
        "unite_dose": "mg",
        "stock": 90,
        "fournisseur": "Merinal",
        "prix_unitaire": 300,
        "indications": ["Œdème", "Hypertension"],
        "contre_indications": ["Déshydratation", "Insuffisance rénale aiguë"],
        "date_expiration": "2025-10-10"
    },
    {
        "id": 17,
        "nom": "Levothyrox",
        "max_duree_prise": 30,
        "forme": "Comprimé",
        "max_dose_jour": 100,
        "unite_dose": "mcg",
        "stock": 150,
        "fournisseur": "Merck",
        "prix_unitaire": 400,
        "indications": ["Hypothyroïdie"],
        "contre_indications": ["Thyrotoxicose non traitée"],
        "date_expiration": "2026-02-15"
    },
]